Fileserver
ximatai/MuYun pull request #26
Opened 2024-10-18 08:27 UTC by Ning19230223

我加入了文件服务功能

2024-10-18 08:44 UTC, gtn1024 requested changes

2024-10-18 08:44 UTC, gtn1024 commented on muyun-boot/src/main/resources/application.yml
> +  upload-path: D:\\file-uploads\\
不应出现你本地文件系统路径

2024-10-18 08:44 UTC, gtn1024 commented on muyun-boot/src/main/resources/application.yml
> +    password: 123456
为什么要改变这个配置？

2024-10-18 08:44 UTC, gtn1024 commented on muyun-boot/src/main/resources/application.yml
> +      url: jdbc:postgresql://localhost:5432/muyun
为什么要改变这个配置？

2024-10-18 08:48 UTC, gtn1024 requested changes

2024-10-18 08:48 UTC, gtn1024 commented on muyun-boot/src/test/java/net/ximatai/muyun/test/fileserver/TestFileserverRouter.java
> +    String nameF;
为什么叫 `nameF`，不叫 `filename`？

2024-10-18 08:48 UTC, gtn1024 commented on muyun-boot/src/test/java/net/ximatai/muyun/test/fileserver/TestFileserverRouter.java
> +    String contextF = "";
？

2024-10-18 08:48 UTC, gtn1024 commented on muyun-fileserver/src/main/java/net/ximatai/muyun/fileserver/FileserverRouter.java
> +    @Route(path = "/fs/index", methods = Route.HttpMethod.GET)
为什么使用 `@Route` 注解，而不是 JAX-RS 的注解？

2024-10-18 08:48 UTC, gtn1024 commented on muyun-fileserver/src/main/java/net/ximatai/muyun/fileserver/FileserverRouter.java
> +    @Route(path = "/fs/form", methods = Route.HttpMethod.POST)
？

2024-10-18 08:48 UTC, gtn1024 commented on muyun-fileserver/src/main/java/net/ximatai/muyun/fileserver/FileserverRouter.java
> +    @Route(path = "/fs/download/:fileUid", methods = Route.HttpMethod.GET)
？

2024-10-18 08:48 UTC, gtn1024 commented on muyun-fileserver/src/main/java/net/ximatai/muyun/fileserver/FileserverRouter.java
> +    @Route(path = "/fs/delete/:uid", methods = Route.HttpMethod.GET)
？

2024-10-18 08:48 UTC, gtn1024 commented on muyun-fileserver/src/main/java/net/ximatai/muyun/fileserver/FileserverRouter.java
> +    @Route(path = "/fs/info/:uid", methods = Route.HttpMethod.GET)
？

2024-10-18 08:55 UTC, gtn1024 requested changes

2024-10-18 08:55 UTC, gtn1024 commented on muyun-boot/src/test/java/net/ximatai/muyun/test/fileserver/TestFileserverRouter.java
> +            e.printStackTrace();
为什么要吞掉报错？

2024-10-18 08:55 UTC, gtn1024 commented on muyun-fileserver/src/main/java/net/ximatai/muyun/fileserver/FileserverRouter.java
> +    public String suffixN(String fileName) {
方法名的意义是什么？

2024-10-18 08:55 UTC, gtn1024 commented on muyun-fileserver/src/main/java/net/ximatai/muyun/fileserver/FileserverRouter.java
> +    public String suffixO(String fileName) {
方法名的意义是什么？

2024-10-18 09:01 UTC, aruis commented on muyun-fileserver/src/main/java/net/ximatai/muyun/fileserver/FileserverRouter.java
> +    @Route(path = "/fs/index", methods = Route.HttpMethod.GET)
> 为什么使用 `@Route` 注解，而不是 JAX-RS 的注解？

因为他是先学习的 vertx ，原始代码实现是vertx版本的。所以考虑先无缝把vertx的相关代码迁移过来。

2024-10-18 09:05 UTC, Ning19230223 commented on muyun-fileserver/src/main/java/net/ximatai/muyun/fileserver/FileserverRouter.java
> +    public String suffixO(String fileName) {
给文件的uid添加后缀，后缀是n表示存储的是文件名，后缀是o表示存储的是文件内容

2024-10-18 09:06 UTC, Ning19230223 commented on muyun-fileserver/src/main/java/net/ximatai/muyun/fileserver/FileserverRouter.java
> +    public String suffixN(String fileName) {
同下

2024-10-18 09:10 UTC, gtn1024 commented on muyun-fileserver/src/main/java/net/ximatai/muyun/fileserver/FileserverRouter.java
> +    public String suffixO(String fileName) {
方法命名应更有意义，如 `suffixFilenameWithO`。
另外将方法设计为 `public` 有什么考虑？

2024-10-18 09:27 UTC, aruis commented on muyun-boot/src/test/java/net/ximatai/muyun/test/fileserver/TestFileserverRouter.java
> +            e.printStackTrace();
任何情况都不要吞掉报错，这是新手常见的错误。

2024-10-18 11:40 UTC, gtn1024 submitted a review, later dismissed

2024-10-21 07:59 UTC, aruis commented on muyun-boot/src/main/resources/application.yml
> +  page-path: /fileserver/
这里叫 path 即可，还要考虑 如果配置的人，没写 / 的兼容性

2024-10-21 08:00 UTC, aruis commented on muyun-boot/src/main/resources/application.yml
> +fileserver:
改成  file-server

2024-10-22 02:25 UTC, aruis approved these changes

2024-10-22 02:26 UTC, Ning19230223 commented on muyun-boot/src/main/resources/application.yml
> +  upload-path: D:\\file-uploads\\
已解决

2024-10-22 02:29 UTC, aruis commented
基本ok了。

2024-10-22 02:29 UTC, merged